# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
