# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190903_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'slug')]),
        ),
    ]
